# Use a lightweight web server container
FROM nginx:alpine

# Copy the HTML, CSS, and JavaScript files to the web server directory
COPY index.html /usr/share/nginx/html/
COPY links.html /usr/share/nginx/html/
COPY styles.css /usr/share/nginx/html/


# Expose port 80
EXPOSE 80

# Command to start the web server
CMD ["nginx", "-g", "daemon off;"]